language:
  node_js
node_js:
  "8"
install:
  - npm install -g codecov
  - npm install -g mocha
  - npm install --save-dev istanbul
  - npm install
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov