language:
  node_js
node_js:
  "8"
install:
  - npm install -g codecov
  - npm install mocha
  - npm install istanbul
  - npm install
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter test/* -- -R spec
  - codecov